[dev]
framework = 'nuxt'

[build]
command = "yarn generate"
publish = "dist"
functions = "functions"

[[headers]]
for = "/sw.js"
[headers.values]
cache-control = "max-age=0,no-cache,no-store,must-revalidate"
[[headers]]
for = "fast.wistia.com/*.js" # js files should be set this way
[headers.values]
cache-control = "public,max-age=604800"
